# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170811_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='list',
            field=models.CharField(max_length=1000, verbose_name='linked from (json format)'),
        ),
    ]
